configuration: Release
image: Visual Studio 2017
xamarin:
  email: christian.schwarz@refactory.at
  password:
    secure: H4gw3tIEpJ6ElrhwcqmSdw==
  android: true
  ios: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
clone_folder: c:\a
init:
#  - cd \
#  - appveyor DownloadFile "http://dl.google.com/android/android-sdk_r24.4.1-windows.zip"
#  - 7z x "android-sdk_r24.4.1-windows.zip" > nul
#  - cd c:\projects\my-project
install:
  - ps: .\scripts\update-version.ps1
#  - echo y | "C:\android-sdk-windows\tools\android" --silent update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-24,extra-android-m2repository,extra-google-m2repository,extra-google-google_play_services
before_build:
- ps: nuget restore
build:
  project: AppShell.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: '**\*.Tests.dll'
deploy:
- provider: NuGet
  name: development
  server: https://www.myget.org/F/appshell/api/v2/package
  api_key:
    secure: 1z5/yKOcTtb7iqitTKq4jfUED7+pQyJkHz5TryyO4hSAvjrKRThI5e0MRVBkxxzx
  symbol_server: https://www.myget.org/F/appshell/api/v2/package
  on:
    branch: master
- provider: NuGet
  name: development tag
  server: https://www.myget.org/F/appshell/api/v2/package
  api_key:
    secure: 1z5/yKOcTtb7iqitTKq4jfUED7+pQyJkHz5TryyO4hSAvjrKRThI5e0MRVBkxxzx
  symbol_server: https://www.myget.org/F/appshell/api/v2/package
  on:
    appveyor_repo_tag: true